# Generated by Django 4.0.6 on 2022-07-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='url',
            new_name='url_text',
        ),
        migrations.AddField(
            model_name='anime',
            name='url_text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
